---
# A sample yaml file
company: itsmartflex
project: crm
networks:
  - name: "10.1.2/24"
    description: "Network for CRM project. 10.1.2/24. !MANAGED BY TERRAFORM!"
    isolated: true
    prefix_length: 24
    ip_pools:
      - start_address: "10.1.2.2"
        end_address: "10.1.2.50"
    gateway: "10.1.2.1"
    guest_vlan_allowed: true
    dhcp_enable: true
    dhcp_pools:
      - start_address: "10.1.2.201"
        end_address: "10.1.2.253"
    dhcp_mode: "NETWORK"
    listener_ip_address: "10.1.2.254"
    dns1: "10.1.2.4"
    dns2: "1.1.1.1"
